add gh-action lint in CI

diff --git a/.github/workflows/code-qa.yaml b/.github/workflows/code-qa.yaml
--- a/.github/workflows/code-qa.yaml
+++ b/.github/workflows/code-qa.yaml
@@ -30,6 +30,27 @@ jobs:
         run: |
           deno fmt --check
 
+  gh-lint:
+    name: Lint GH actions
+    runs-on: ubunutu-24.04
+    steps:
+      - name: actionlint
+        id: actionlint
+        uses: raven-actions/actionlint@v2
+        with:
+          cache: false  # optional
+
+      - name: actionlint Summary
+        if: failure()
+        run: |
+          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
+          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
+          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
+          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
+          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
+          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
+          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"
+          exit ${{ steps.actionlint.outputs.exit-code }}
   lint:
     name: Lint the project
     runs-on: ubuntu-24.04
